name: CreateRelease

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies Pt.1
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libtag1-dev libmusicbrainz5-dev libcurl4-openssl-dev libneon-dev libjansson-dev libxml2-dev

      - name: Install Dependencies Pt.2
        run: |
          git clone https://github.com/metabrainz/libcoverart
          cd libcoverart
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel
          sudo cmake --install build


      - name: Build
        run: |
          cmake -B build -DCMAKE-BUILD_TYPE=Release
          cmake --build build --parallel

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare Artifacts
        run: |
          cp build/trax build/trax_linux_x86_64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/trax_linux_x86_64
            simple_install.sh
          generate_release_notes: true
          prerelease: false
