jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make libtag1-dev libmusicbrainz5-dev libcurl4-openssl-dev libcoverart-dev
      - name: Build Trax
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel
      - name: Prepare Artifacts
        run: |
          cp build/trax build/trax_linux_x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/trax_linux_x86_64
            install_runtime_dependencies.sh
          generate_release_notes: true
          prerelease: false

  publish-image:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_CNT_TRAX }}
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: containers/Containerfile
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/trax:latest
            ghcr.io/${{ github.repository_owner }}/trax:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}